# Generated by Django 6.0.7 on 2026-07-29 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'HUNTER'}, on_delete=django.db.models.deletion.CASCADE, related_name='hunter_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sheriff',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'SHERIFF'}, on_delete=django.db.models.deletion.CASCADE, related_name='sheriff_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
