# Generated by Django 6.0.7 on 2026-07-29 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0002_alter_hunter_user_alter_sheriff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountymission',
            name='hunter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='bounties.hunter'),
        ),
        migrations.AlterField(
            model_name='bountymission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Disponible'), ('IN_PROGRESS', 'En cours'), ('CAPTURED', 'Cible capturée'), ('KILLED', 'Cible éliminée'), ('FAILED', 'Échec')], default='OPEN', max_length=15),
        ),
    ]
