# Generated by Django 6.0.7 on 2026-07-29 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0003_alter_bountymission_hunter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bountymission',
            old_name='agreed_reward',
            new_name='reward',
        ),
        migrations.RemoveField(
            model_name='wantedperson',
            name='reward',
        ),
    ]
