# Generated by Django 6.0.7 on 2026-07-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0004_rename_agreed_reward_bountymission_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bountymission',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='bountymission',
            name='started_at',
        ),
        migrations.AddField(
            model_name='bountymission',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bountymission',
            name='claimed_result',
            field=models.CharField(blank=True, choices=[('CAPTURED', 'Cible capturée'), ('KILLED', 'Cible éliminée')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bountymission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Disponible'), ('PENDING_VERIFICATION', 'En attente de vérification'), ('CAPTURED', 'Capture validée'), ('KILLED', 'Élimination validée')], default='OPEN', max_length=20),
        ),
    ]
