# Generated by Django 6.0.7 on 2026-07-30 10:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0005_remove_bountymission_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bountymission',
            name='reward',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='bountymission',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Disponible'), ('PENDING_VERIFICATION', 'En attente de vérification'), ('CAPTURED', 'Capture validée'), ('KILLED', 'Élimination validée'), ('CANCELLED', 'Annulée')], default='OPEN', max_length=20),
        ),
    ]
